### ISSUE TITLE
Disabling spawn all creatures.

### ISSUE THREAD

**Issue by Tkhakiro** [John-Development/mobproof_end_crystals_mod#13]
In your mod, really miss the optional ability to disable the spawn of all creatures (hostile, neutral and peaceful) in the "working" radius of the crystal.

**Comment by John-Development** [comment]
Thats a good thing to have as a configurable option.
Although I dont see the benefit in disabling pacific mobs entirely (they can be disabled in vanilla by overflowing the pacific mobcap in the spawnchunks). Could be better to have a configurable list of mobs that should not spawn, with options like
#pacific
#hostile
#aquatic
#all
Specific mobs

**Comment by Tkhakiro** [comment]
I think fans of skyblocks will find it very useful to completely disable the possibility of all possible creatures appearing.

**Comment by John-Development** [comment]
It has been added in the latest version (2.4.0) so Im closing the issue, thank you for the feedback!
