### ISSUE TITLE
Newest version crashes on start (mob-proof-crystals-2.4.0-1.20.jar)

### ISSUE THREAD

**Issue by Tkhakiro** [John-Development/mobproof_end_crystals_mod#14]
[tl console.log](https://github.com/John-Development/mobproof-end-crystals-mod/files/15319529/tl.console.log)

There was no problem with the previous version.

**Comment by John-Development** [comment]
Looks like you are using 1.20.1, the last update is for 1.20.6 only, as that version broke a lot of things, most of the mods you have should be updated by now so it should not be a problem

**Comment by Tkhakiro** [comment]
It's not a problem. Then I will use your mod the next time I update the entire mod assembly to newer versions of minecraft that are relevant at that moment.

**Comment by Tkhakiro** [comment]
It's not a problem. Then I will use your mod the next time I update the entire mod assembly to newer versions of minecraft that are relevant at that moment.
